name: FVG Bot Scan

on:
  schedule:
    - cron: '30 8 * * 1-5'
    - cron: '35 8 * * 1-5'
    - cron: '40 8 * * 1-5'
    - cron: '45 8 * * 1-5'
    - cron: '50 8 * * 1-5'
    - cron: '55 8 * * 1-5'
    - cron: '0 9 * * 1-5'
    - cron: '5 9 * * 1-5'
    - cron: '10 9 * * 1-5'
    - cron: '15 9 * * 1-5'
    - cron: '20 9 * * 1-5'
    - cron: '25 9 * * 1-5'
    - cron: '30 9 * * 1-5'
    - cron: '35 9 * * 1-5'
    - cron: '40 9 * * 1-5'
    - cron: '45 9 * * 1-5'
    - cron: '50 9 * * 1-5'
    - cron: '55 9 * * 1-5'
    - cron: '0 10 * * 1-5'
    - cron: '5 10 * * 1-5'
    - cron: '10 10 * * 1-5'
    - cron: '15 10 * * 1-5'
    - cron: '20 10 * * 1-5'
    - cron: '25 10 * * 1-5'
    - cron: '30 10 * * 1-5'

jobs:
  run-fvg-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install yfinance pandas
      - name: Run FVG Scanner
        run: python fvg_bot.py
