name: Alle 10 Minuten Mo–Fr (08–21 Uhr DE)

on:
  schedule:
       - cron: '30 8 * * 1-5'
    - cron: '35 8 * * 1-5'
    - cron: '40 8 * * 1-5'
    - cron: '45 8 * * 1-5'
    - cron: '50 8 * * 1-5'
    - cron: '55 8 * * 1-5'
    - cron: '0 9 * * 1-5'
    - cron: '5 9 * * 1-5'
    - cron: '10 9 * * 1-5'
    - cron: '15 9 * * 1-5'
    - cron: '20 9 * * 1-5'
    - cron: '25 9 * * 1-5'
    - cron: '30 9 * * 1-5'
    - cron: '35 9 * * 1-5'
    - cron: '40 9 * * 1-5'
    - cron: '45 9 * * 1-5'
    - cron: '50 9 * * 1-5'
    - cron: '55 9 * * 1-5'
    - cron: '0 10 * * 1-5'
    - cron: '5 10 * * 1-5'
    - cron: '10 10 * * 1-5'
    - cron: '15 10 * * 1-5'
    - cron: '20 10 * * 1-5'
    - cron: '25 10 * * 1-5'
    - cron: '30 10 * * 1-5'

  workflow_dispatch:

jobs:
  run-dax-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v3

      - name: 🐍 Python 3.10 installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 💾 Cache pip-Abhängigkeiten
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 📦 Abhängigkeiten installieren
        run: pip install -r requirements.txt

      - name: 🚀 Bot ausführen
        run: python -u Dax.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
